const images = {
  slider1: require('./images/slider/paldrive-promo2.png'),
  slider2: require('./images/slider/paldrive-promo3.png'),
  slider3: require('./images/slider/paldrive-promo-old.png'),
  activity: require('./images/activity.png'),
  activity_selected: require('./images/activity_selected.png'),
  add: require('./images/add.png'),
  add_selected: require('./images/add_selected.png'),
  home: require('./images/home.png'),
  home_selected: require('./images/home_selected.png'),
  profile: require('./images/profile.png'),
  profile_selected: require('./images/profile_selected.png'),
  search: require('./images/search.png'),
  search_selected: require('./images/search_selected.png'),
  photo_camera: require('./images/photo_camera.png'),
  photo_gallary: require('./images/photo_gallary.png'),
  direct_message: require('./images/direct_message.png'),
  logo: require('./images/paldrive_logo.png'),
  tLogo: require('./images/titleLogo.png'),
  wLogo: require('./images/wLogo.jpg'),
  more: require('./images/more.png'),
  bookmark: require('./images/bookmark.png'),
  like: require('./images/like.png'),
  favorite: require('./images/favorite.png'),
  favorite_select: require('./images/fav_select.png'),
  comment: require('./images/comment.png'),
  settings: require('./images/settings.png'),
  flash: require('./images/flash.png'),
  close: require('./images/close.png'),
  logoBlack: require('./images/logoBlack.png'),
  facebookLogo: require('./images/facebookLogo.png'),
  backButton: require('./images/backButton.png'),
  plusIcon: require('./images/plusIcon.png'),
  test: require('./images/test.png'),
  addIcon: require('./images/addIcon.png'),
  searchInputIcon: require('./images/searchInputIcon.png'),
  dmBackButton: require('./images/dmBackButton.png'),
  bookmarkWhite: require('./images/bookmarkWhite.png'),
  videoCamera: require('./images/video_camera.png'),
  write: require('./images/write.png'),
  dot: require('./images/dot.png'),
  dmBottomCamera: require('./images/dmBottomCamera.png'),
  grid: require('./images/gridIcon.png'),
  list3: require('./images/list3.png'),
  avatar: require('./images/avatar.png'),
  emoji_icon: require('./images/emoji.png'),
  send_message: require('./images/send_message.png'),

  ///dummy images
  av1: require('./images/ic1.png'),
  av2: require('./images/ic2.png'),
  av3: require('./images/ic3.png'),
  av4: require('./images/ic4.png'),
  av6: require('./images/ic6.png'),
  
  pro1: require('./images/pro1.jpg'),
  pro2: require('./images/pro2.jpg'),
  pro3: require('./images/pro3.jpg'),
  pro4: require('./images/pro4.jpg'),
  pro5: require('./images/pro5.jpg'),
  pro6: require('./images/pro6.jpg'),
  pro7: require('./images/pro7.jpg'),
  pro8: require('./images/pro8.jpg'),
  pro9: require('./images/pro9.jpg'),
};

export default images;
